apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-test
  namespace: dev
  labels:
    app: cache-test
spec:
  selector:
    matchLabels:
      app: cache-test
  template:
    metadata:
      labels:
        app: cache-test
    spec:
      containers:
      - name: cache-test
        image: <docker image>
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cache-test
  namespace: dev
  labels:
    app: cache-test
spec:
  selector:
    app: cache-test
  ports:
  - port: 5000
    targetPort: 5000
    name: http
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cache-test-gw
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - cache-test.example.com
    tls:
      httpsRedirect: true
  - port:
      name: https-443
      number: 443
      protocol: HTTP
    hosts:
    - cache-test.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cache-test-vs
  namespace: dev
spec:
  hosts:
  - cache-test.example.com
  gateways:
  - cache-test-gw
  http:
  - route:
    - destination:
        host: cache-test.dev.svc.cluster.local
        port:
          number: 5000

